# Generated by Django 4.2.2 on 2023-06-26 07:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_skill_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='myblog',
            unique_together={('title', 'slug')},
        ),
    ]
