# Generated by Django 4.2.2 on 2023-06-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_myblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_description', models.TextField(blank=True, null=True)),
                ('happy_client', models.IntegerField(null=True)),
                ('project', models.IntegerField(null=True)),
                ('cup_of_coffee', models.IntegerField(null=True)),
                ('award', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
