# Generated by Django 4.2.2 on 2023-06-26 07:57

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_myblog_slug_alter_myblog_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='image', unique=True),
        ),
    ]
