# Generated by Django 4.2.4 on 2023-09-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_skill_unique_together_alter_skill_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myblog',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='myblog',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
