# Generated by Django 4.2.2 on 2023-06-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='subject',
            field=models.CharField(choices=[('A', 'App'), ('W', 'Web'), ('C', 'Card')], max_length=3, null=True),
        ),
    ]
