# Generated by Django 4.2.4 on 2023-09-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_myblog_unique_together_alter_myblog_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='typewritter',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
