# Generated by Django 4.2.2 on 2023-06-25 02:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
