# Generated by Django 4.2.2 on 2023-06-25 02:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_about_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='fact_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
