# Generated by Django 4.2.2 on 2023-06-25 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_skill_skill_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_description',
        ),
    ]
